### PR TITLE
Some additional filters

### PR DESCRIPTION
**Pull request by Willdotwhite**
Added:
- Skills sought
- Preferred tools

### CODE REVIEW

**Comment by Willdotwhite** [comment]
@dallonf can you point me in the right direction please? I've read back through #84 but I can't find this Skills fix to ~steal~ reference

**Review by dallonf — DISMISSED** [review]
I gotcha covered :)

**Comment by dallonf** [comment]
oh no now typescript problems

**Comment by Willdotwhite** [comment]
That's fine, I can looking into my terrible TS now, cheers 👍

**Comment by dallonf** [comment]
Nope, got that too :)

**Review by dallonf — APPROVED** [review]

**Pull request merged**
