### PR TITLE
MyPost: Add title and availability fields

### PR DESCRIPTION
**Pull request by Willdotwhite**

### CODE REVIEW

**Comment by dallonf** [comment]
@Willdotwhite Care to review my changes?

**Review by dallonf — DISMISSED** [review]

**Comment by dallonf** [comment]
whoops nvm I broke the tests

**Comment by Willdotwhite** [comment]
Oh nice, thanks for fixing the whole localStorage thing - felt grim adding that in.

LGTM @dallonf as soon as the tests are passing 😇

**Comment by Willdotwhite** [comment]
Test failure just looks like `Availability` is declared twice, phew - thought it might be something gnarly

**Pull request merged**
